---
name: test
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version:
          - 2.7
          - "3.0"
    name: Ruby ${{ matrix.ruby_version }}
    env:
      BUNDLE_WITHOUT: extras

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec spec
